import { Image } from 'react-native';

interface TripUpLogoProps {
  size?: number;
}

// simple logo component - wraps the logo png so i can drop it anywhere with a consistent size
//logo generated by chatgpt
export function TripUpLogo({ size = 120 }: TripUpLogoProps) {
  return (
    <Image
      source={require('@/assets/images/tripuplogo.png')}
      style={{
        width: size,
        height: size,
        resizeMode: 'contain',
      }}
    />
  );
}

export default TripUpLogo;
